global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'restapi'
    static_configs:
      - targets: ['restapi:8001']

  - job_name: 'graphql'
    static_configs:
      - targets: ['graphql:8000']
