services:
  restapi:
    container_name: restapi
    build: 
      context: ./form_submission
    ports:
      - 8001:8001
    volumes:
      - restapi_data:/uploaded_files
      
  graphql:
    container_name: graphql
    build: 
      context: ./verification_service
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: doctors_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  restapi_data:
      