interface DistrictList {
  name: string;
  district: string;
}

const district: DistrictList[] = [
  { district: "Koshi Pradesh", name: "Bhojpur" },
  { district: "Koshi Pradesh", name: "Dhankuta" },
  { district: "Koshi Pradesh", name: "Ilam" },
  { district: "Koshi Pradesh", name: "Jhapa" },
  { district: "Koshi Pradesh", name: "Khotang" },
  { district: "Koshi Pradesh", name: "Morang" },
  { district: "Koshi Pradesh", name: "Okhaldhunga" },
  { district: "Koshi Pradesh", name: "Panchthar" },
  { district: "Koshi Pradesh", name: "Sankhuwasabha" },
  { district: "Koshi Pradesh", name: "Solukhumbu" },
  { district: "Koshi Pradesh", name: "Sunsari" },
  { district: "Koshi Pradesh", name: "Taplejung" },
  { district: "Koshi Pradesh", name: "Tehrathum" },
  { district: "Koshi Pradesh", name: "Udayapur" },
  { district: "Madhesh Province", name: "Parsa" },
  { district: "Madhesh Province", name: "Bara" },
  { district: "Madhesh Province", name: "Rautahat" },
  { district: "Madhesh Province", name: "Sarlahi" },
  { district: "Madhesh Province", name: "Dhanusha" },
  { district: "Madhesh Province", name: "Siraha" },
  { district: "Madhesh Province", name: "Mahottari" },
  { district: "Madhesh Province", name: "Saptari" },
  { district: "Bagmati Province", name: "Sindhuli" },
  { district: "Bagmati Province", name: "Ramechhap" },
  { district: "Bagmati Province", name: "Dolakha" },
  { district: "Bagmati Province", name: "Bhaktapur" },
  { district: "Bagmati Province", name: "Dhading" },
  { district: "Bagmati Province", name: "Kathmandu" },
  { district: "Bagmati Province", name: "Kavrepalanchok" },
  { district: "Bagmati Province", name: "Lalitpur" },
  { district: "Bagmati Province", name: "Nuwakot" },
  { district: "Bagmati Province", name: "Rasuwa" },
  { district: "Bagmati Province", name: "Sindhupalchok" },
  { district: "Bagmati Province", name: "Chitwan" },
  { district: "Bagmati Province", name: "Makwanpur" },
  { district: "Gandaki Province", name: "Baglung" },
  { district: "Gandaki Province", name: "Gorkha" },
  { district: "Gandaki Province", name: "Kaski" },
  { district: "Gandaki Province", name: "Lamjung" },
  { district: "Gandaki Province", name: "Manang" },
  { district: "Gandaki Province", name: "Mustang" },
  { district: "Gandaki Province", name: "Myagdi" },
  {
    district: "Gandaki Province",
    name: "Nawalparasi (East of Bardaghat Susta)",
  },
  { district: "Gandaki Province", name: "Parbat" },
  { district: "Gandaki Province", name: "Syangja" },
  { district: "Gandaki Province", name: "Tanahun" },
  { district: "Lumbini Province", name: "Kapilvastu" },
  {
    district: "Lumbini Province",
    name: "Nawalparasi (West of Bardaghat Susta)",
  },
  { district: "Lumbini Province", name: "Rupandehi" },
  { district: "Lumbini Province", name: "Arghakhanchi" },
  { district: "Lumbini Province", name: "Gulmi" },
  { district: "Lumbini Province", name: "Palpa" },
  { district: "Lumbini Province", name: "Dang" },
  { district: "Lumbini Province", name: "Pyuthan" },
  { district: "Lumbini Province", name: "Rolpa" },
  { district: "Lumbini Province", name: "Eastern Rukum" },
  { district: "Lumbini Province", name: "Banke" },
  { district: "Lumbini Province", name: "Bardiya" },
  { district: "Karnali Province", name: "Western Rukum" },
  { district: "Karnali Province", name: "Salyan" },
  { district: "Karnali Province", name: "Dolpa" },
  { district: "Karnali Province", name: "Humla" },
  { district: "Karnali Province", name: "Jumla" },
  { district: "Karnali Province", name: "Kalikot" },
  { district: "Karnali Province", name: "Mugu" },
  { district: "Karnali Province", name: "Surkhet" },
  { district: "Karnali Province", name: "Dailekh" },
  { district: "Karnali Province", name: "Jajarkot" },
  { district: "Sudurpashchim Province", name: "Kailali" },
  { district: "Sudurpashchim Province", name: "Achham" },
  { district: "Sudurpashchim Province", name: "Doti" },
  { district: "Sudurpashchim Province", name: "Bajhang" },
  { district: "Sudurpashchim Province", name: "Bajura" },
  { district: "Sudurpashchim Province", name: "Kanchanpur" },
  { district: "Sudurpashchim Province", name: "Dadeldhura" },
  { district: "Sudurpashchim Province", name: "Baitadi" },
  { district: "Sudurpashchim Province", name: "Darchula" },
];

export default district;
